{
//=========Macro generated from canvas: Ratio_Multi2Incl_AlphaT55/Ratio_Multi2Incl_AlphaT55
//=========  (Tue Jul  5 19:06:33 2011) by ROOT version5.27/06b
   TCanvas *Ratio_Multi2Incl_AlphaT55 = new TCanvas("Ratio_Multi2Incl_AlphaT55", "Ratio_Multi2Incl_AlphaT55",0,0,800,600);
   gStyle->SetOptStat(0);
   Ratio_Multi2Incl_AlphaT55->Range(204.6872,-1.902439e-05,464.1744,0.0001273171);
   Ratio_Multi2Incl_AlphaT55->SetFillColor(0);
   Ratio_Multi2Incl_AlphaT55->SetBorderMode(0);
   Ratio_Multi2Incl_AlphaT55->SetBorderSize(2);
   Ratio_Multi2Incl_AlphaT55->SetTickx(1);
   Ratio_Multi2Incl_AlphaT55->SetTicky(1);
   Ratio_Multi2Incl_AlphaT55->SetLeftMargin(0.17);
   Ratio_Multi2Incl_AlphaT55->SetRightMargin(0.05);
   Ratio_Multi2Incl_AlphaT55->SetTopMargin(0.05);
   Ratio_Multi2Incl_AlphaT55->SetBottomMargin(0.13);
   Ratio_Multi2Incl_AlphaT55->SetFrameFillStyle(0);
   Ratio_Multi2Incl_AlphaT55->SetFrameBorderMode(0);
   Ratio_Multi2Incl_AlphaT55->SetFrameFillStyle(0);
   Ratio_Multi2Incl_AlphaT55->SetFrameBorderMode(0);
   
   TMultiGraph *multigraph = new TMultiGraph();
   multigraph->SetName("");
   multigraph->SetTitle("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(10);
   grae->SetName("Graph");
   grae->SetTitle("SM (nominal)");
   grae->SetFillColor(1);
   grae->SetMarkerStyle(20);
   grae->SetMarkerSize(2);
   grae->SetPoint(0,260,0);
   grae->SetPointError(0,10,10,0,0);
   grae->SetPoint(1,280,0);
   grae->SetPointError(1,10,10,0,0);
   grae->SetPoint(2,300,0);
   grae->SetPointError(2,10,10,0,0);
   grae->SetPoint(3,320,0);
   grae->SetPointError(3,10,10,0,0);
   grae->SetPoint(4,340,0);
   grae->SetPointError(4,10,10,0,0);
   grae->SetPoint(5,360,0);
   grae->SetPointError(5,10,10,0,0);
   grae->SetPoint(6,380,0);
   grae->SetPointError(6,10,10,0,0);
   grae->SetPoint(7,400,0);
   grae->SetPointError(7,10,10,0,0);
   grae->SetPoint(8,420,0);
   grae->SetPointError(8,10,10,0,0);
   grae->SetPoint(9,440,0);
   grae->SetPointError(9,10,10,0,0);
   
   TH1F *Graph1 = new TH1F("Graph1","SM (nominal)",100,230,470);
   Graph1->SetMinimum(0);
   Graph1->SetMaximum(1.1);
   Graph1->SetDirectory(0);
   Graph1->SetStats(0);
   Graph1->SetFillColor(63);
   Graph1->SetLineStyle(0);
   Graph1->SetMarkerStyle(20);
   Graph1->GetXaxis()->SetNdivisions(1005);
   Graph1->GetXaxis()->SetLabelFont(42);
   Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph1->GetXaxis()->SetLabelSize(0.05);
   Graph1->GetXaxis()->SetTitleSize(0.06);
   Graph1->GetXaxis()->SetTitleOffset(0.9);
   Graph1->GetXaxis()->SetTitleFont(42);
   Graph1->GetYaxis()->SetLabelFont(42);
   Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph1->GetYaxis()->SetLabelSize(0.05);
   Graph1->GetYaxis()->SetTitleSize(0.06);
   Graph1->GetYaxis()->SetTitleOffset(1.05);
   Graph1->GetYaxis()->SetTitleFont(42);
   Graph1->GetZaxis()->SetLabelFont(42);
   Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph1->GetZaxis()->SetLabelSize(0.05);
   Graph1->GetZaxis()->SetTitleSize(0.06);
   Graph1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph1);
   
   multigraph->Add(grae,"p");
   multigraph->Draw("a");
   multigraph->GetXaxis()->SetTitle("H_{T} (GeV)");
   multigraph->GetXaxis()->SetRange(5,96);
   multigraph->GetXaxis()->SetNdivisions(1005);
   multigraph->GetXaxis()->SetLabelFont(42);
   multigraph->GetXaxis()->SetLabelOffset(0.007);
   multigraph->GetXaxis()->SetLabelSize(0.05);
   multigraph->GetXaxis()->SetTitleSize(0.06);
   multigraph->GetXaxis()->SetTitleOffset(0.9);
   multigraph->GetXaxis()->SetTitleFont(42);
   multigraph->GetYaxis()->SetTitle("R_{#alpha_{T}}(H_{T})");
   multigraph->GetYaxis()->SetLabelFont(42);
   multigraph->GetYaxis()->SetLabelOffset(0.007);
   multigraph->GetYaxis()->SetLabelSize(0.05);
   multigraph->GetYaxis()->SetTitleSize(0.06);
   multigraph->GetYaxis()->SetTitleOffset(1.3);
   multigraph->GetYaxis()->SetTitleFont(42);
   
   TLegend *leg = new TLegend(0.6,0.65,0.8,0.85,NULL,"brNDC");
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","SM (nominal)","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(2);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.9,"#scale[0.8]{CMS preliminary 2011}");
tex->SetNDC();
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.9,"#scale[0.8]{#int L dt = 320 pb^{-1}, #sqrt{s} = 7 TeV}");
tex->SetNDC();
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   Ratio_Multi2Incl_AlphaT55->Modified();
   Ratio_Multi2Incl_AlphaT55->cd();
   Ratio_Multi2Incl_AlphaT55->SetSelected(Ratio_Multi2Incl_AlphaT55);
}
